[project]
name = "constolution"
version = "0.1.0"
readme = "README.rst"
dependencies = [
    "torch>=2.4.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/constolution"]
